language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer self-update && composer --version
  - composer install

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=./coverage.txt
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.txt

after_script:
  - make benchmark
